name: Maven Test

on:
  push:
    branches:
      - jsoup-tests-parser
      - jsoup-tests-helper
  pull_request:
    branches:
      - jsoup-tests-parser
      - jsoup-tests-helper
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'
          cache: 'maven'

      - name: Run Maven tests
        run: mvn -X verify -B --file pom.xml
